
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Nov  1 2019 03:21:15 IST (Oct 31 2019 21:51:15 UTC)

// Verification Directory fv/radix4fft 

module radix4fft(x, yReal, yImag);
  input [3:0] x;
  output [11:0] yReal, yImag;
  wire [3:0] x;
  wire [11:0] yReal, yImag;
  wire n_0, n_1, n_2, n_3, n_5, n_6, n_8, n_10;
  assign yImag[0] = 1'b0;
  assign yImag[1] = 1'b0;
  assign yImag[2] = 1'b0;
  assign yImag[3] = yImag[9];
  assign yImag[4] = yImag[5];
  assign yImag[6] = 1'b0;
  assign yImag[7] = 1'b0;
  assign yImag[8] = 1'b0;
  assign yImag[10] = yImag[11];
  assign yReal[0] = yReal[6];
  assign yReal[3] = yReal[9];
  assign yReal[4] = yReal[11];
  assign yReal[5] = yReal[11];
  assign yReal[10] = yReal[11];
  OAI222XL g289(.A0 (n_8), .A1 (n_10), .B0 (n_3), .B1 (n_0), .C0 (n_5),
       .C1 (x[0]), .Y (yReal[1]));
  MXI2XL g291(.A (n_10), .B (yReal[9]), .S0 (yImag[9]), .Y (yReal[6]));
  AO21X1 g290(.A0 (n_8), .A1 (n_6), .B0 (yReal[8]), .Y (yReal[7]));
  OAI32XL g292(.A0 (x[0]), .A1 (x[2]), .A2 (n_8), .B0 (n_6), .B1 (n_5),
       .Y (yReal[8]));
  INVXL g293(.A (yReal[9]), .Y (n_10));
  OAI21XL g296(.A0 (n_1), .A1 (x[2]), .B0 (n_2), .Y (yReal[9]));
  NOR2XL g294(.A (n_5), .B (n_3), .Y (yReal[2]));
  OR2X1 g295(.A (yImag[11]), .B (yImag[5]), .Y (yImag[9]));
  INVXL g298(.A (n_2), .Y (yReal[11]));
  NAND2XL g301(.A (x[2]), .B (n_1), .Y (n_2));
  INVXL g302(.A (n_5), .Y (n_0));
  INVXL g297(.A (n_3), .Y (n_6));
  NOR2XL g304(.A (x[1]), .B (x[3]), .Y (n_8));
  NOR2BXL g303(.AN (x[3]), .B (x[1]), .Y (yImag[11]));
  NOR2BXL g299(.AN (x[1]), .B (x[3]), .Y (yImag[5]));
  NAND2XL g300(.A (x[0]), .B (x[2]), .Y (n_3));
  NAND2XL g305(.A (x[1]), .B (x[3]), .Y (n_5));
  INVXL g306(.A (x[0]), .Y (n_1));
endmodule

