/*
###############################################################
#  Generated by:      Cadence Innovus 16.21-s078_1
#  OS:                Linux x86_64(Host ID client04)
#  Generated on:      Fri Nov  1 03:47:34 2019
#  Design:            radix2fft
#  Command:           saveNetlist radix2fft-innovus-netlist.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Nov  1 2019 03:19:34 IST (Oct 31 2019 21:49:34 UTC)
// Verification Directory fv/radix2fft 
module dftcalc (
	x, 
	y, 
	x1, 
	x2);
   input x;
   input y;
   output [2:0] x1;
   output [2:0] x2;

   // Internal wires
   wire n_1;
   wire n_4;

   CLKINVX1 g53 (.A(n_4),
	.Y(x1[0]));
   ADDHXL g54 (.A(y),
	.B(n_1),
	.CO(x2[2]),
	.S(n_4));
   NOR2BXL g55 (.AN(y),
	.B(n_1),
	.Y(x1[1]));
   CLKINVX1 g56 (.A(x),
	.Y(n_1));
endmodule

module dftcalc_1 (
	x, 
	y, 
	x1, 
	x2);
   input x;
   input y;
   output [2:0] x1;
   output [2:0] x2;

   // Internal wires
   wire n_1;
   wire n_4;

   CLKINVX1 g53 (.A(n_4),
	.Y(x1[0]));
   ADDHXL g54 (.A(y),
	.B(n_1),
	.CO(x2[2]),
	.S(n_4));
   NOR2BXL g55 (.AN(y),
	.B(n_1),
	.Y(x1[1]));
   CLKINVX1 g56 (.A(x),
	.Y(n_1));
endmodule

module radix2fft (
	x, 
	yReal, 
	yImag);
   input [3:0] x;
   output [11:0] yReal;
   output [11:0] yImag;

   // Internal wires
   wire [11:0] temp;
   wire UNCONNECTED;
   wire UNCONNECTED0;
   wire UNCONNECTED1;
   wire UNCONNECTED2;
   wire UNCONNECTED3;
   wire UNCONNECTED4;
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire \temp[1]_16 ;

   assign yImag[0] = 1'b0 ;
   assign yImag[1] = 1'b0 ;
   assign yImag[2] = 1'b0 ;
   assign yImag[3] = yImag[9] ;
   assign yImag[6] = 1'b0 ;
   assign yImag[7] = 1'b0 ;
   assign yImag[8] = 1'b0 ;
   assign yImag[10] = yImag[11] ;
   assign yReal[0] = yReal[6] ;
   assign yReal[3] = yReal[9] ;
   assign yReal[4] = yReal[11] ;
   assign yReal[5] = yReal[11] ;
   assign yReal[10] = yReal[11] ;

   dftcalc A (.x(x[0]),
	.y(x[2]),
	.x1({ UNCONNECTED,
		\temp[1]_16 ,
		yReal[9] }),
	.x2({ yReal[11],
		UNCONNECTED1,
		UNCONNECTED0 }));
   dftcalc_1 B (.x(x[1]),
	.y(x[3]),
	.x1({ UNCONNECTED2,
		temp[7],
		yImag[9] }),
	.x2({ yImag[11],
		UNCONNECTED4,
		UNCONNECTED3 }));
   OAI21XL g242 (.A0(n_9),
	.A1(n_2),
	.B0(n_5),
	.Y(yReal[8]));
   MXI2XL g243 (.A(n_9),
	.B(n_1),
	.S0(n_7),
	.Y(yReal[7]));
   OAI21XL g244 (.A0(n_4),
	.A1(n_7),
	.B0(n_8),
	.Y(yReal[1]));
   CLKINVX1 g245 (.A(n_1),
	.Y(n_9));
   NAND2XL g246 (.A(n_7),
	.B(n_4),
	.Y(n_8));
   OAI2BB1XL g247 (.A0N(\temp[1]_16 ),
	.A1N(temp[7]),
	.B0(n_6),
	.Y(yReal[2]));
   OAI21XL g248 (.A0(temp[7]),
	.A1(\temp[1]_16 ),
	.B0(n_3),
	.Y(n_6));
   NAND2BXL g249 (.AN(n_2),
	.B(n_5),
	.Y(n_7));
   AO21X1 g250 (.A0(yImag[11]),
	.A1(n_0),
	.B0(yImag[5]),
	.Y(yImag[4]));
   AO21X1 g251 (.A0(yReal[9]),
	.A1(n_0),
	.B0(n_1),
	.Y(yReal[6]));
   CLKINVX1 g252 (.A(n_4),
	.Y(n_3));
   NAND2BXL g253 (.AN(\temp[1]_16 ),
	.B(temp[7]),
	.Y(n_5));
   NAND2XL g254 (.A(yReal[9]),
	.B(yImag[9]),
	.Y(n_4));
   NOR2BXL g255 (.AN(\temp[1]_16 ),
	.B(temp[7]),
	.Y(n_2));
   NOR2XL g256 (.A(yImag[11]),
	.B(n_0),
	.Y(yImag[5]));
   NOR2XL g257 (.A(yReal[9]),
	.B(n_0),
	.Y(n_1));
   CLKINVX1 g258 (.A(yImag[9]),
	.Y(n_0));
endmodule

